name: Build

on:
  workflow_call:

permissions:
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_ARM64_TESTING: 1

jobs:
  build:
    strategy:
      matrix:
        os: [
          # ubuntu-22.04,     # linux-amd64
          # ubuntu-22.04-arm, # linux-arm64
          macos-13,         # darwin-amd64 (Intel)
          macos-latest      # darwin-arm64 (Apple Silicon) - uses standard runner
        ]
        # include:
          # Add container config for Linux builds only
          # - os: ubuntu-22.04
          #   container: '{"image": "ghcr.io/homebrew/ubuntu22.04:main", "options": "--user=linuxbrew"}'
          #   workdir: /github/home
          # - os: ubuntu-22.04-arm
          #   container: '{"image": "ghcr.io/homebrew/ubuntu22.04:main", "options": "--user=linuxbrew"}'
          #   workdir: /github/home
      fail-fast: false
    runs-on: ${{matrix.os}}
    container: ${{matrix.container && fromJSON(matrix.container) || ''}}
    defaults:
      run:
        working-directory: ${{matrix.workdir || github.workspace}}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - name: Build Portable Ruby
        run: |
          mkdir -p bottle/
          cd bottle
          brew portable-package --verbose portable-ruby --no-test

      - name: Upload Portable Ruby
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bottles_${{matrix.os}}
          path: ${{matrix.workdir || github.workspace}}/bottle

      # - name: Test Portable Ruby
      #   run: |
      #     mkdir -p portable-ruby/
      #     tar --strip-components 2 -C portable-ruby -xf bottle/portable-ruby--*.tar.gz
      #     export PATH="${PWD}/portable-ruby/bin:${PATH}"
      #     export HOMEBREW_USE_RUBY_FROM_PATH=1
      #     rm -rf "$(brew --repo)/Library/Homebrew/vendor/portable-ruby"
      #     brew config | awk -v s="${PWD}/portable-ruby/bin/ruby" '$0~s{r=1} 1; END{exit(!r)}'

      - name: Post cleanup
        if: always()
        run: |
          brew test-bot --only-cleanup-after
          rm -rvf bottle portable-ruby
